server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: chat-server
  kafka:
    topic:
      direct-message: direct-message-topic
      direct-action: direct-action-topic
      read-status: read-status-topic
      direct-upload: direct-upload-topic
    consumer:
      group-id:
        direct-message: direct-message
        direct-action: direct-action
        read-status: read-status
        direct-upload: direct-upload
      auto-offset-reset: latest
      enable-auto-commit: false
      properties:
        heartbeat.interval.ms: 3000
        session.timeout.ms: 60000  # 60초 동안 하트비트 없으면 죽은 것으로 판단
        max.poll.interval.ms: 1800000  # 30분 동안 폴링 없으면 세션 종료 방지
        max.poll.records: 500  # 한번에 가져오는 메시지 수
        connections.max.idle.ms: 1800000  # 30분 동안 연결 유지
        request.timeout.ms: 120000  # 2분 동안 응답 없으면 재시도
        retry.backoff.ms: 1000  # 재연결 백오프 (1초)

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, refresh
    
logging:
  level:
    com.asyncgate.chat_server: DEBUG
